# Site settings
title: Mauricio Klein's Blog
tagline:
email: mauricio.klein.msk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Developer at Zenvia Mobile Results
# baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://mauricioklein.github.io"
logourl: /assets/images/logo.png
author: "Mauricio Klein"
author_thumbnail: "/assets/images/avatar.jpg"

# Theme customization - please change from the defaults!
theme:
  highlight_color: "#205081" #205081" # "#272935"

  social:
    github: mauricioklein
    facebook: mauricioklein
    # gplus: +gayanvirajith
    # dribble: gayanvirajith
    # pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: mauricio_kleins_blog

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key:
  google_webmaster_key:

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Pagination config
paginate: 5

# Excerpt Separator
excerpt_separator: <!-- More -->

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - Dockerfile
  - dockerRun.sh

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
